version: "3.9"

services:
  nginx:
    container_name: "ca-nginx-form"
    image: nginx:1.23.1
    # `working_dir` - sets the working directory of the container that is created
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    container_name: "ca-php-form"
    build: ./docker/php/
    # `working_dir` - sets the working directory of the container that is created
    working_dir: /var/www
    volumes:
      - ./src:/var/www
