<!doctype html>
<html lang="lt">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Registracija į kursus</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link rel="stylesheet" href="/css/styles.css">

</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-sm-12 my-5">


            <h1><a href="/">Registraciija į kursus</a></h1>


            <div id="error" class="alert alert-danger d-none" role="alert"></div>


            <div class="card ">
                <form method="POST" enctype="multipart/form-data" id="user-reg">
                    <div class="card-body">


                        <div class="row my-3">
                            <div class="col-4">
                                <label for="f-name" class="form-label required">Vardas</label>
                            </div>
                            <div class="col-8">
                                <input id="f-name" name="f_name" class="form-control" type="text" required>
                            </div>
                        </div>

                        <div class="row my-3">
                            <div class="col-4">
                                <label for="l-name" class="form-label required">Pavardė</label>
                            </div>
                            <div class="col-8">
                                <input id="l-name" name="l_name" class="form-control" type="text" required>
                            </div>
                        </div>

                        <div class="row my-3">
                            <div class="col-4">
                                <label for="city" class="form-label required">Miestas</label>
                            </div>
                            <div class="col-8">
                                <select id="city" class="form-select" name="city" required>
                                    <!-- empty selection -->
                                    <option disabled selected>pasirinkti miestą</option>
                                    <option value="vilnius">Vilnius</option>
                                    <option value="kaunas">Kaunas</option>
                                    <option value="klaipeda">Klaipėda</option>
                                </select>
                            </div>
                        </div>

                        <div class="row my-5">

                            <div class="col-4">
                                <p class="required">Programavimo kalba</p>
                            </div>
                            <div class="col-8">

                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="lang[]" value="cpp"
                                           id="defaultCheck1">
                                    <label class="form-check-label" for="defaultCheck1">
                                        C++
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="lang[]" value="php"
                                           id="defaultCheck2">
                                    <label class="form-check-label" for="defaultCheck2">
                                        PHP
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="lang[]" value="pyt"
                                           id="defaultCheck3">
                                    <label class="form-check-label" for="defaultCheck3">
                                        Python
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="row my-3">
                            <div class="col-4">
                                <p class="required">Papildoma informacija</p>
                            </div>
                            <div class="col-8">
                                <textarea class="form-control" name="info" rows="4" cols="50" maxlength="50"
                                          placeholder="pvz.: turiu C++ programavimo patirties" required></textarea>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-4">
                                <label for="formFile" class="form-label required">Profilio nuotrauka</label>
                            </div>
                            <div class="col-8">
                                <input class="form-control" type="file" id="formFile" name="user-image" required>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-4"></div>
                            <div class="col-8">
                                <button class="btn btn-success">Registruotis</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>


        <div class="col-lg-6 col-sm-12 my-5">

            <div id="result" class="d-none">


                <h1>Registracijos duomenys</h1>


                <div class="card">
                    <ul class="list-group list-group-flush">
                        <li id="res-fname" class="list-group-item">Vardas:</li>
                        <li id="res-lname" class="list-group-item">Pavardė:</li>
                        <li id="res-city" class="list-group-item">Miestas:</li>
                        <li id="res-langs" class="list-group-item">Programavimo kalba:</li>
                        <li id="res-info" class="list-group-item">Papildoma informacija:</li>
                        <li class="list-group-item">
                            <img id="res-img" class="img-fluid" src=""
                                 alt="user image">
                        </li>
                    </ul>
                </div>

            </div>

        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>

<script src="/js/app.js"></script>
</body>
</html>
